"""生成 Palace WSL2 Windows 侧 wrapper（tools/ 资产，不入 git 的唯一仓内事实源）。

背景（runs/palace_spike/wsl_validation.md + bridge_criteria.md）：
Palace 官方只有 Linux 预编译二进制（palace-x86_64.bin，ELF），Windows 侧
python subprocess 无法直启；本工作区的二进制装在 WSL2 发行版 rfauto-ubuntu
内、产物回拷在 <repo>/tools/palace-install/bin/。adapter（palace_solver.py）
以 `[exe, config]` 两元命令直启 exe——Windows 下需要一个 Windows 可执行的
wrapper 把调用转进 WSL。

本脚本幂等生成两个 wrapper 文件（内容钉成单一事实源，ASCII-only、.sh 为 LF）：

  tools/palace-install/bin/palace.cmd    —— Windows 侧入口（adapter exe 探测命中它）
  tools/palace-install/bin/palace_wsl.sh —— WSL 侧路径转换 + exec 官方 bash wrapper

用法：
  python scripts/palace_wsl_wrapper.py            # 写出/刷新两个 wrapper
  python scripts/palace_wsl_wrapper.py --check    # 只校验在位内容一致（CI/门用）

wrapper 契约（细节见 runs/palace_spike/bridge_criteria.md §2）：
  palace.cmd [OPTIONS] CONFIG_FILE
  - CONFIG_FILE 为 Windows 侧绝对路径，helper 内 wslpath -u 转 WSL 路径；
  - 工作目录由 wsl.exe 继承映射（/mnt/<盘>/...），Palace 相对 Output 落回
    同一 Windows 工作目录；
  - 调用方未传 -np/-serial/-launcher 时缺省 -serial（WSL root 下 OpenMPI
    需 --allow-run-as-root，串行是开箱即用最小路径；并行由调用方显式传
    `-np N -launcher-args "--allow-run-as-root"`）；
  - wsl.exe 管道输出是 UTF-16LE（#271 家族），消费侧需 NUL 剥除/重解码。
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BIN_DIR = REPO_ROOT / "tools" / "palace-install" / "bin"
WSL_DISTRO = "rfauto-ubuntu"

# Windows 盘符段形态（Path.parts 首段）：'E:\\' / 'E:' / 'E:/'（E-MED-6
# 护栏：POSIX 首段 '/' 或相对路径首段在此提取出空串 → /mnt// 静默坏路径，
# 改为显式报错）。
_DRIVE_SEG_RE = re.compile(r"^[A-Za-z]:[\\/]?$")

# 生成文件内容一律 ASCII-only（cmd 按系统码页解析、bash 对编码敏感，
# 坑账 #89/#271：绝不往工具脚本里写非 ASCII 字符）。
PALACE_CMD_TEMPLATE = """\
@echo off
rem Palace WSL2 launcher for rfauto (generated by scripts/palace_wsl_wrapper.py,
rem do not hand-edit: regenerate instead).
rem Usage: palace.cmd CONFIG_FILE [OPTIONS...]
rem   CONFIG_FILE (FIRST argument, Windows-side absolute path) is passed into
rem   WSL via the PALACE_WINCFG env var + WSLENV, because wsl.exe mangles
rem   backslashes in argv (bridge smoke evidence 2026-09-23). OPTIONS pass
rem   through to the official bash wrapper (-serial / -np / -nt / -launcher ...).
rem Working directory: inherited by wsl.exe and mapped to /mnt/<drive>/...,
rem so Palace writes its relative Output dir back into the Windows workdir.
rem Output encoding: wsl.exe emits UTF-16LE when piped; consumers must strip
rem NULs or re-decode (see runs/palace_spike/wsl_validation.md section 6).
setlocal EnableExtensions
set "SCRIPT_DIR=%~dp0"
set "WSL_DISTRO={distro}"
set "HELPER_LOCAL=%SCRIPT_DIR%palace_wsl.sh"
set "HELPER_WSL={helper_wsl}"
if "%~1"=="" (
  echo palace.cmd: usage: palace.cmd CONFIG_FILE [OPTIONS...] 1>&2
  exit /b 2
)
set "FIRST_ARG=%~1"
if "%FIRST_ARG:~0,1%"=="-" (
  echo palace.cmd: CONFIG_FILE must be the first argument, got option "%~1" 1>&2
  exit /b 2
)
if not exist "%HELPER_LOCAL%" (
  echo palace.cmd: missing helper palace_wsl.sh next to this script 1>&2
  exit /b 127
)
set "PALACE_WINCFG=%~f1"
if defined WSLENV (set "WSLENV=PALACE_WINCFG:%WSLENV%") else set "WSLENV=PALACE_WINCFG"
wsl.exe -d %WSL_DISTRO% --exec bash "%HELPER_WSL%" %*
endlocal & exit /b %ERRORLEVEL%
"""

PALACE_WSL_SH = """\
#!/bin/bash
# Palace WSL helper (generated by scripts/palace_wsl_wrapper.py,
# do not hand-edit: regenerate instead).
# Config path arrives via PALACE_WINCFG env (WSLENV shared by palace.cmd)
# because wsl.exe mangles backslashes in argv; the first non-flag argv
# positional is dropped (it is the mangled duplicate). Options pass through.
# Defaults to -serial unless -np/-serial/-launcher is passed (OpenMPI as
# root inside WSL needs --allow-run-as-root; serial is the safe default).
# LD_LIBRARY_PATH: the back-ported .bin carries no RPATH; private prefix
# libs (PETSc/SLEPc/...) live in the distro at $PALACE_LIB_DIR (default
# /root/palace_ws/prefix/lib, set inside WSL to override).
set -u
BIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"

CFG=""
if [ -n "${PALACE_WINCFG:-}" ]; then
  CFG="$(wslpath -u "$PALACE_WINCFG")"
fi

ARGS=()
DROPPED_CFG=0
HAS_MPI_CHOICE=0
for a in "$@"; do
  case "$a" in
    -np|--np|-serial|--serial|-sequential|--sequential|-launcher|--launcher)
      ARGS+=("$a")
      HAS_MPI_CHOICE=1
      ;;
    -*)
      ARGS+=("$a")
      ;;
    *)
      if [ "$DROPPED_CFG" -eq 0 ]; then
        DROPPED_CFG=1
        if [ -z "$CFG" ]; then
          CFG="$(wslpath -u "$a" 2>/dev/null || printf '%s' "$a")"
        fi
      else
        ARGS+=("$a")
      fi
      ;;
  esac
done

if [ "$HAS_MPI_CHOICE" -eq 0 ]; then
  ARGS+=("-serial")
fi

if [ -z "$CFG" ]; then
  echo "palace_wsl.sh: no CONFIG_FILE (set PALACE_WINCFG or pass a path argument)" 1>&2
  exit 2
fi

PALACE_LIB_DIR="${PALACE_LIB_DIR:-/root/palace_ws/prefix/lib}"
if [ -d "$PALACE_LIB_DIR" ]; then
  export LD_LIBRARY_PATH="$PALACE_LIB_DIR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
fi

exec bash "$BIN_DIR/palace" "${ARGS[@]}" "$CFG"
"""


def extract_drive_letter(parts: tuple[str, ...]) -> str:
    """从 Path.parts 提取盘符字母（纯函数，跨平台可测；E-MED-6 护栏）。

    首段须为 Windows 盘符形态（'E:\\\\'/'E:'/'E:/'，bridge_criteria §2 实测
    Path.parts 首段带反斜杠尾）；否则 ValueError——历史代码对 '/' 或相对
    路径静默提取出空串得 /mnt// 坏路径，现显式报错。
    """
    if not parts or not _DRIVE_SEG_RE.fullmatch(parts[0]):
        raise ValueError(
            f"Palace WSL wrapper 仅支持 Windows 盘符路径布局（安装于 "
            f"<盘>:/...），收到首段 {parts[0] if parts else '<empty>'!r}；"
            f"parts={parts!r}"
        )
    return "".join(ch for ch in parts[0] if ch.isalnum()).lower()


def _wsl_helper_path() -> str:
    """helper 的 WSL 侧绝对路径（固定安装布局：<盘>:/<仓库根> → /mnt/<盘>/...）。"""
    parts = BIN_DIR.parts
    drive = extract_drive_letter(parts)
    return "/mnt/" + drive + "/" + "/".join(parts[1:]) + "/palace_wsl.sh"


def build_palace_cmd() -> str:
    return PALACE_CMD_TEMPLATE.format(distro=WSL_DISTRO,
                                      helper_wsl=_wsl_helper_path())


def build_palace_wsl_sh() -> str:
    return PALACE_WSL_SH


def _normalize_lf(text: str) -> bytes:
    """统一 LF 行尾 + 结尾单换行（bash 对 CRLF 零容忍）。"""
    text = text.replace("\r\n", "\n")
    if not text.endswith("\n"):
        text += "\n"
    return text.encode("ascii")


# 官方 wrapper（WSL 源码构建产物回拷 tools/ 时曾被 Windows 侧按文本传输转成
# CRLF——bridge 冒烟首跑实证：bash 报 $'\\r': command not found）。bash 脚本
# 一律 LF；生成器顺带修复（白名单点名，幂等）。
_OFFICIAL_SH_FILES = ("palace", "validate-config")


def fix_official_wrapper_crlf() -> list[str]:
    """把官方 bash wrapper 的 CRLF 行尾规范为 LF（已在 LF 则零改动）。"""
    fixed: list[str] = []
    for name in _OFFICIAL_SH_FILES:
        p = BIN_DIR / name
        if not p.is_file():
            continue
        raw = p.read_bytes()
        if b"\r\n" not in raw:
            continue
        p.write_bytes(raw.replace(b"\r\n", b"\n"))
        fixed.append(name)
    return fixed


def targets() -> list[tuple[Path, bytes]]:
    return [
        (BIN_DIR / "palace.cmd", _normalize_lf(build_palace_cmd())),
        (BIN_DIR / "palace_wsl.sh", _normalize_lf(build_palace_wsl_sh())),
    ]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Generate the Windows-side Palace WSL wrapper assets "
                    "(tools/palace-install/bin/).")
    ap.add_argument("--check", action="store_true",
                    help="verify installed wrappers match the pinned content "
                         "without writing")
    args = ap.parse_args(argv)

    for path, content in targets():
        if args.check:
            if not path.exists():
                print(f"MISSING: {path}")
                return 1
            actual = path.read_bytes()
            if actual != content:
                print(f"DRIFT: {path} differs from pinned content "
                      f"(regenerate without --check)")
                return 1
            print(f"OK: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            existed = path.exists()
            path.write_bytes(content)
            print(f"{'REFRESH' if existed else 'WROTE'}: {path}")
    if not args.check:
        for name in fix_official_wrapper_crlf():
            print(f"LF-FIXED (CRLF -> LF): {BIN_DIR / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
