"""色散材料库：Debye / Djordjevic-Sarkar 因果宽带介电模型。

背景
----
模板库现有基板全部是常数 εr，宽带（>10 GHz 或超宽带）没有因果性保障。
本模块提供两类**确定性**（纯 numpy，无网络、无求解器）色散介电模型，
数据源 = 厂商 datasheet 单频点 (εr, tanδ) → 因果拟合：

* **Debye（单极 / 多极）**：ε(ω) = ε∞ + Σ_i Δε_i / (1 + j ω τ_i)
* **Djordjevic-Sarkar（D-S）**：以 1/f 加权、在 [f1, f2] 上连续叠加 Debye
  弛豫的因果宽带模型 [1]：

      ε(ω) = ε∞ + Δε / ln(f2/f1) · ln[(f2 + j f) / (f1 + j f)]

D-S 的**结构性因果保证**：它等价于无穷多 Debye 极点（每个极点单独满足
Kramers-Kronig 关系）的非负加权叠加，故整体必然满足 K-K。模块另提供
kramers_kronig_residual() 数值自检与 equivalent_debye() 有限多极对照。

口径与来源（与 openEMS 官方实现逐行对齐）
-----------------------------------------
openEMS 原生支持该模型，接口为
AddDjordjevicSarkarMaterial(CSX, name, 'fMeas', ..., 'epsRMeas', ...,
'tandMeas', ..., 'f1', ..., 'f2', ...)，内部调用
CalcDjordjevicSarkarApprox 由**单频点测量 + 频带端点**拟合：

* 官方文档（确证原生支持）：
  https://openems.readthedocs.io/en/latest/octave/autogenerated/CSXCAD/AddDjordjevicSarkarMaterial.html
* 参考实现（本工作区 vendor）：
  vendor/openEMS/install/share/CSXCAD/matlab/CalcDjordjevicSarkarApprox.m
  单点拟合（lowFreqEvalType=0）：

      k  = ln(10)·(-tanδ·εr - σ_DC/(ε0·ω_m)) / arg[(ω2 + jω_m)/(ω1 + jω_m)]
      ε∞ = εr - k·log10|(ω2 + jω_m)/(ω1 + jω_m)|
      Δε = k·(m2 - m1),   m = log10(ω),  ω = 2πf

* 符号约定：ε = ε' - jε''，tanδ = -Im(ε)/Re(ε) ≥ 0（与 openEMS 一致）。

文献
----
[1] A. R. Djordjevic, R. M. Biljie, V. D. Likar-Smiljanic, T. K. Sarkar,
    "Wideband frequency-domain characterization of FR-4 and time-domain
    causality," IEEE Trans. Electromagn. Compat., vol. 43, no. 4,
    pp. 662-667, 2001.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
import yaml

__all__ = [
    "C0",
    "EPS0",
    "DebyeModel",
    "DebyePole",
    "DjordjevicSarkar",
    "epsilon_analytic_ds",
    "fit_djordjevic_sarkar",
    "kramers_kronig_residual",
    "load_dispersion_material",
]

#: 真空介电常数 (F/m)，与 openEMS CalcDjordjevicSarkarApprox.m 取值一致
EPS0 = 8.8541878128e-12
#: 真空光速 (m/s)
C0 = 299792458.0


# ─── 输入校验与求值辅助 ────────────────────────────────────────────────────────

def _positive(name: str, value: Any) -> float:
    """校验正的有限标量并返回 float。"""
    out = float(value)
    if not np.isfinite(out) or out <= 0.0:
        raise ValueError(f"{name} 必须为正的有限值，收到 {value!r}")
    return out


def _non_negative(name: str, value: Any) -> float:
    """校验非负的有限标量并返回 float。"""
    out = float(value)
    if not np.isfinite(out) or out < 0.0:
        raise ValueError(f"{name} 必须为非负的有限值，收到 {value!r}")
    return out


def _freq_array(freq_hz: Any) -> tuple[np.ndarray, bool]:
    """把频率入参收敛为 1-D float 数组，并报告原入参是否为标量。"""
    scalar = np.ndim(freq_hz) == 0
    arr = np.atleast_1d(np.asarray(freq_hz, dtype=float))
    if not np.all(np.isfinite(arr)):
        raise ValueError("频率必须为有限值（Hz）")
    if np.any(arr <= 0.0):
        raise ValueError("频率必须为正（Hz）")
    return arr, scalar


def _squeeze(values: np.ndarray, scalar: bool) -> Any:
    """标量输入时把长度为 1 的结果还原为标量。"""
    return values[0] if scalar else values


# ─── Debye 弛豫模型 ───────────────────────────────────────────────────────────

class DebyePole:
    """单个 Debye 弛豫极点：Δε / (1 + j f/f_relax)。"""

    __slots__ = ("delta_eps", "f_relax_hz")

    def __init__(self, delta_eps: float, f_relax_hz: float) -> None:
        self.delta_eps = _positive("delta_eps", delta_eps)
        self.f_relax_hz = _positive("f_relax_hz", f_relax_hz)

    def __repr__(self) -> str:  # pragma: no cover - 可读性辅助
        return f"DebyePole(delta_eps={self.delta_eps!r}, f_relax_hz={self.f_relax_hz!r})"

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, DebyePole):
            return NotImplemented
        return self.delta_eps == other.delta_eps and self.f_relax_hz == other.f_relax_hz


class DebyeModel:
    """单极 / 多极 Debye 复介电常数模型（纯 numpy，确定性）。

    ε(ω) = ε∞ + Σ_i Δε_i / (1 + j ω / ω_i) - j σ_DC/(ω ε0)
    """

    def __init__(self, eps_inf: float, poles: Any = (), sigma_dc: float = 0.0) -> None:
        self.eps_inf = _positive("eps_inf", eps_inf)
        self.sigma_dc = _non_negative("sigma_dc", sigma_dc)
        self.poles = tuple(poles)
        for pole in self.poles:
            if not isinstance(pole, DebyePole):
                raise TypeError(f"poles 元素必须是 DebyePole，收到 {type(pole).__name__}")

    # -- 求值 ---------------------------------------------------------------
    def epsilon(self, freq_hz: Any) -> Any:
        """复相对介电常数 ε = ε' - jε''（标量输入返回标量）。"""
        freq, scalar = _freq_array(freq_hz)
        omega = 2.0 * np.pi * freq
        eps = np.full(freq.shape, complex(self.eps_inf), dtype=complex)
        for pole in self.poles:
            eps = eps + pole.delta_eps / (1.0 + 1j * omega / (2.0 * np.pi * pole.f_relax_hz))
        if self.sigma_dc:
            eps = eps - 1j * self.sigma_dc / (omega * EPS0)
        return _squeeze(eps, scalar)

    def epsilon_r(self, freq_hz: Any) -> Any:
        """实部 ε'(f)。"""
        return np.real(self.epsilon(freq_hz))

    def loss_tangent(self, freq_hz: Any) -> Any:
        """损耗角正切 tanδ = -Im(ε)/Re(ε)。"""
        eps = np.asarray(self.epsilon(freq_hz), dtype=complex)
        return -eps.imag / eps.real

    # -- openEMS 导出 -------------------------------------------------------
    def to_openems(self) -> dict[str, Any]:
        """导出 openEMS AddDebyeMaterial 可直接消费的参数。

        字段对应 openEMS 材料属性：epsilon=ε∞、kappa=σ_DC，
        以及逐极点的 EpsilonDelta_i / EpsilonRelaxTime_i（τ=1/ω_i）。
        """
        return {
            "model": "debye",
            "epsilon": self.eps_inf,
            "kappa": self.sigma_dc,
            "poles": [
                {
                    "delta_eps": pole.delta_eps,
                    "f_relax_hz": pole.f_relax_hz,
                    "relax_time_s": 1.0 / (2.0 * np.pi * pole.f_relax_hz),
                }
                for pole in self.poles
            ],
        }


# ─── Djordjevic-Sarkar 因果宽带模型 ───────────────────────────────────────────

class DjordjevicSarkar:
    """Djordjevic-Sarkar 因果宽带介电模型。

    ε(ω) = ε∞ + Δε/ln(ω2/ω1) · ln[(ω2 + jω)/(ω1 + jω)] - j σ_DC/(ω ε0)

    其中 ω1 = 2π f1、ω2 = 2π f2 是频带端点（D-S 的下/上角频率）。
    """

    def __init__(
        self,
        eps_inf: float,
        delta_eps: float,
        f1_hz: float,
        f2_hz: float,
        sigma_dc: float = 0.0,
        *,
        f_meas_hz: float | None = None,
        eps_r_meas: float | None = None,
        tan_delta_meas: float | None = None,
    ) -> None:
        self.eps_inf = _positive("eps_inf", eps_inf)
        self.delta_eps = _non_negative("delta_eps", delta_eps)
        self.f1_hz = _positive("f1_hz", f1_hz)
        self.f2_hz = _positive("f2_hz", f2_hz)
        if self.f1_hz >= self.f2_hz:
            raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={self.f1_hz!r}, f2={self.f2_hz!r}")
        self.sigma_dc = _non_negative("sigma_dc", sigma_dc)

        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        self.m1 = float(np.log10(omega1))
        self.m2 = float(np.log10(omega2))

        self.f_meas_hz = None if f_meas_hz is None else _positive("f_meas_hz", f_meas_hz)
        self.eps_r_meas = None if eps_r_meas is None else _positive("eps_r_meas", eps_r_meas)
        self.tan_delta_meas = (
            None if tan_delta_meas is None else _non_negative("tan_delta_meas", tan_delta_meas)
        )

    # -- 单点拟合（openEMS 口径）--------------------------------------------
    @classmethod
    def from_single_point(
        cls,
        eps_r: float,
        loss_tangent: float,
        f_meas_hz: float,
        f1_hz: float,
        f2_hz: float,
        sigma_dc: float = 0.0,
    ) -> DjordjevicSarkar:
        """由单频点 (εr, tanδ) + 频带端点 [f1, f2] 反解 D-S 参数。

        与 openEMS CalcDjordjevicSarkarApprox（lowFreqEvalType=0）完全同口径：
        模型在 f_meas 处**精确**回代 εr 与 tanδ。
        """
        eps_r = _positive("eps_r", eps_r)
        loss_tangent = _non_negative("loss_tangent", loss_tangent)
        f_meas = _positive("f_meas_hz", f_meas_hz)
        f1 = _positive("f1_hz", f1_hz)
        f2 = _positive("f2_hz", f2_hz)
        sigma = _non_negative("sigma_dc", sigma_dc)
        if f1 >= f2:
            raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={f1!r}, f2={f2!r}")

        omega1 = 2.0 * np.pi * f1
        omega2 = 2.0 * np.pi * f2
        omega_m = 2.0 * np.pi * f_meas
        m1 = float(np.log10(omega1))
        m2 = float(np.log10(omega2))

        ratio = (omega2 + 1j * omega_m) / (omega1 + 1j * omega_m)
        k = np.log(10.0) * (-loss_tangent * eps_r - sigma / (EPS0 * omega_m)) / np.angle(ratio)
        eps_inf = eps_r - k * np.log10(abs(ratio))
        delta_eps = k * (m2 - m1)

        return cls(
            eps_inf=eps_inf,
            delta_eps=delta_eps,
            f1_hz=f1,
            f2_hz=f2,
            sigma_dc=sigma,
            f_meas_hz=f_meas,
            eps_r_meas=eps_r,
            tan_delta_meas=loss_tangent,
        )

    # -- 求值 ---------------------------------------------------------------
    def epsilon(self, freq_hz: Any) -> Any:
        """复相对介电常数 ε = ε' - jε''（标量输入返回标量）。"""
        freq, scalar = _freq_array(freq_hz)
        omega = 2.0 * np.pi * freq
        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        eps = self.eps_inf + self.delta_eps / (self.m2 - self.m1) * np.log10(
            (omega2 + 1j * omega) / (omega1 + 1j * omega)
        )
        if self.sigma_dc:
            eps = eps - 1j * self.sigma_dc / (omega * EPS0)
        return _squeeze(eps, scalar)

    def epsilon_r(self, freq_hz: Any) -> Any:
        """实部 ε'(f)。"""
        return np.real(self.epsilon(freq_hz))

    def loss_tangent(self, freq_hz: Any) -> Any:
        """损耗角正切 tanδ = -Im(ε)/Re(ε)。"""
        eps = np.asarray(self.epsilon(freq_hz), dtype=complex)
        return -eps.imag / eps.real

    # -- 结构 / 因果 ---------------------------------------------------------
    def static_eps_r(self) -> float:
        """ε(f→0) = ε∞ + Δε（D-S 的 DC 静态值）。"""
        return float(self.eps_inf + self.delta_eps)

    def sarkar_parameters(self) -> dict[str, float]:
        """D-S 原始参数（openEMS paramSarkar 同构）。"""
        return {
            "eps_inf": self.eps_inf,
            "delta_eps": self.delta_eps,
            "f1_hz": self.f1_hz,
            "f2_hz": self.f2_hz,
            "m1": self.m1,
            "m2": self.m2,
            "sigma_dc": self.sigma_dc,
        }

    def equivalent_debye(self, n_terms_per_dec: int = 1) -> DebyeModel:
        """按 openEMS CalcDjordjevicSarkarApprox 口径拟合有限多极 Debye。

        极点对数分布（>=1 个/十倍频程），Δε_i 由 D-S 虚部在对数取样点上的
        线性方程组求得，ε∞ 保证参考频点处实部一致。
        """
        terms = int(n_terms_per_dec)
        if terms < 1:
            raise ValueError(f"n_terms_per_dec 必须 >= 1，收到 {n_terms_per_dec!r}")
        n_terms = int(np.ceil((self.m2 - self.m1) * terms)) + 1
        m_i = np.linspace(self.m1, self.m2, n_terms)
        omega_i = 10.0**m_i
        m_sp = 10.0 ** ((np.log10(omega_i[1]) - np.log10(omega_i[0])) / 4.0)
        omega_meas = omega_i * m_sp

        a = 1.0 / (omega_i[None, :] / omega_meas[:, None] + omega_meas[:, None] / omega_i[None, :])
        eps_pp = -np.imag(self.epsilon(omega_meas / (2.0 * np.pi)))
        delta_eps_i = np.linalg.solve(a, eps_pp)

        f_ref = self.f_meas_hz if self.f_meas_hz is not None else float(np.sqrt(self.f1_hz * self.f2_hz))
        omega_ref = 2.0 * np.pi * f_ref
        sum_real = float(np.sum(delta_eps_i / (1.0 + omega_ref**2 / omega_i**2)))
        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        log_abs = np.log10(abs((omega2 + 1j * omega_ref) / (omega1 + 1j * omega_ref)))
        eps_inf_debye = self.eps_inf + self.delta_eps / (self.m2 - self.m1) * log_abs - sum_real

        poles = [
            DebyePole(delta_eps=float(de), f_relax_hz=float(wi / (2.0 * np.pi)))
            for de, wi in zip(delta_eps_i, omega_i, strict=True)
        ]
        return DebyeModel(eps_inf=float(eps_inf_debye), poles=poles, sigma_dc=self.sigma_dc)

    def to_openems(self, n_terms_per_dec: int = 1) -> dict[str, Any]:
        """导出 openEMS 材料参数（多极 Debye 编码，即官方内部形式）。

        AddDjordjevicSarkarMaterial 内部就是先拟合多极 Debye，再用
        AddDebyeMaterial + EpsilonDelta_i / EpsilonRelaxTime_i 落材料。
        返回值可直接映射到这些 openEMS 材料属性。
        """
        payload = self.equivalent_debye(n_terms_per_dec).to_openems()
        payload["model"] = "djordjevic_sarkar"
        payload["sarkar"] = self.sarkar_parameters()
        return payload

    def to_openems_sarkar_kwargs(self) -> dict[str, Any]:
        """AddDjordjevicSarkarMaterial 的 name-value 参数（单点拟合入口）。

        无测量元数据时取频带几何中点为等价参考点，反解出的 kwargs 可自洽地
        令 openEMS 重新拟合出同一模型。
        """
        if self.f_meas_hz is not None and self.eps_r_meas is not None and self.tan_delta_meas is not None:
            f_ref, eps_r, tan_d = self.f_meas_hz, self.eps_r_meas, self.tan_delta_meas
        else:
            f_ref = float(np.sqrt(self.f1_hz * self.f2_hz))
            eps_r = float(self.epsilon_r(f_ref))
            tan_d = float(self.loss_tangent(f_ref))
        return {
            "fMeas": f_ref,
            "epsRMeas": eps_r,
            "tandMeas": tan_d,
            "f1": self.f1_hz,
            "f2": self.f2_hz,
            "lowFreqEvalType": 0,
            "sigmaDC": self.sigma_dc,
        }


# ─── 独立解析对照（复对数路径之外的实/虚部闭式）──────────────────────────────

def epsilon_analytic_ds(
    eps_inf: float,
    delta_eps: float,
    f1_hz: float,
    f2_hz: float,
    freq_hz: Any,
    sigma_dc: float = 0.0,
) -> Any:
    """D-S 的实/虚部独立闭式（不含 np.log 复数路径，供交叉校验）。

        ε'(ω) = ε∞ + Δε/ln(ω2/ω1) · ½ln[(ω2²+ω²)/(ω1²+ω²)]
        ε''(ω) = Δε/ln(ω2/ω1) · [arctan(ω/ω1) - arctan(ω/ω2)]
    """
    eps_inf = _positive("eps_inf", eps_inf)
    delta_eps = _non_negative("delta_eps", delta_eps)
    f1 = _positive("f1_hz", f1_hz)
    f2 = _positive("f2_hz", f2_hz)
    sigma = _non_negative("sigma_dc", sigma_dc)
    if f1 >= f2:
        raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={f1!r}, f2={f2!r}")

    freq, scalar = _freq_array(freq_hz)
    omega = 2.0 * np.pi * freq
    omega1 = 2.0 * np.pi * f1
    omega2 = 2.0 * np.pi * f2
    ln_ratio = np.log(omega2 / omega1)

    eps_real = eps_inf + delta_eps / ln_ratio * 0.5 * np.log((omega2**2 + omega**2) / (omega1**2 + omega**2))
    eps_imag = delta_eps / ln_ratio * (np.arctan(omega / omega2) - np.arctan(omega / omega1))
    eps = eps_real + 1j * eps_imag
    if sigma:
        eps = eps - 1j * sigma / (omega * EPS0)
    return _squeeze(eps, scalar)


def fit_djordjevic_sarkar(
    eps_r: float,
    loss_tangent: float,
    f_meas_hz: float,
    f1_hz: float,
    f2_hz: float,
    sigma_dc: float = 0.0,
) -> DjordjevicSarkar:
    """由单频点 (εr, tanδ) + 频带端点拟合 D-S 模型（from_single_point 别名）。"""
    return DjordjevicSarkar.from_single_point(eps_r, loss_tangent, f_meas_hz, f1_hz, f2_hz, sigma_dc)


# ─── Kramers-Kronig 数值自检 ─────────────────────────────────────────────────

def kramers_kronig_residual(
    model: DebyeModel | DjordjevicSarkar,
    freq_hz: Any,
    *,
    n_points: int = 100001,
    span_decades: float = 20.0,
) -> Any:
    """在主值意义下数值检验实部 K-K 关系，返回相对残差。

        ε'(ω) - ε∞ = (2/π) P ∫_0^∞ ξ ε''(ξ)/(ξ² - ω²) dξ

    积分经 t = ln(ξ/ω) 换元后核函数为奇函数，对称半格点梯形求积可消去
    1/(2t) 主值奇异项。要求 σ_DC = 0（电导项的 K-K 需额外减除项）。
    """
    if getattr(model, "sigma_dc", 0.0) != 0.0:
        raise ValueError("K-K 自检要求 sigma_dc=0（电导项的 K-K 需额外减除项）")
    n = int(n_points)
    if n < 1001:
        raise ValueError(f"n_points 必须 >= 1001，收到 {n_points!r}")
    span = _positive("span_decades", span_decades)
    eps_inf = _positive("eps_inf", model.eps_inf)

    freq, scalar = _freq_array(freq_hz)
    t_max = span * np.log(10.0)
    t = (np.arange(-n, n) + 0.5) * (t_max / n)
    kernel = 1.0 / (1.0 - np.exp(-2.0 * t))

    residual = np.empty(freq.shape, dtype=float)
    for idx, f0 in enumerate(freq):
        xi = f0 * np.exp(t)
        eps_xi = np.asarray(model.epsilon(xi), dtype=complex)
        lhs = (2.0 / np.pi) * np.trapezoid(-eps_xi.imag * kernel, t)
        eps_at = complex(np.asarray(model.epsilon(f0), dtype=complex))
        rhs = eps_at.real - eps_inf
        residual[idx] = abs(lhs - rhs) / abs(rhs) if rhs != 0.0 else abs(lhs)
    return _squeeze(residual, scalar)


# ─── materials.yaml 色散条目加载 ─────────────────────────────────────────────

def _materials_path(config_path: str | Path | None) -> Path:
    if config_path is None:
        # project root: src/rfauto/core/ -> src/rfauto/ -> src/ -> project root
        return Path(__file__).resolve().parent.parent.parent.parent / "configs" / "materials.yaml"
    return Path(config_path)


def load_dispersion_material(
    name: str,
    config_path: str | Path | None = None,
) -> DjordjevicSarkar:
    """从 configs/materials.yaml 的 dispersion 子段构造 D-S 模型。"""
    path = _materials_path(config_path)
    if not path.exists():
        raise FileNotFoundError(f"materials.yaml 不存在: {path}")
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}

    materials = data.get("materials", {})
    if name not in materials:
        raise KeyError(f"未知材料: {name}，可用: {list(materials)}")
    block = materials[name].get("dispersion")
    if not block:
        raise KeyError(f"材料 {name} 没有 dispersion 条目")

    model = str(block.get("model", "")).strip().lower()
    if model != "djordjevic_sarkar":
        raise ValueError(f"不支持的色散模型: {model!r}（材料 {name}）")

    return DjordjevicSarkar.from_single_point(
        eps_r=float(block["eps_r_meas"]),
        loss_tangent=float(block["tan_delta_meas"]),
        f_meas_hz=float(block["f_meas_hz"]),
        f1_hz=float(block["f1_hz"]),
        f2_hz=float(block["f2_hz"]),
        sigma_dc=float(block.get("sigma_dc", 0.0)),
    )
