"""色散材料库（D1，§10.4）：Debye / Djordjevic-Sarkar / Lorentz 因果介电模型
+ 多频点向量拟合面。

背景
----
模板库现有基板全部是常数 εr，宽带（>10 GHz 或超宽带）没有因果性保障。
本模块提供**确定性**（纯 numpy，无网络、无求解器）色散介电模型：

* **Debye（单极 / 多极）**：ε(ω) = ε∞ + Σ_i Δε_i / (1 + j ω τ_i)
* **Lorentz 振子（W4-C P13，2026-10-05）**：ε(f) = ε∞ + Σ Δε_i·f0_i²/
  (f0_i²−f²+jf·γ_i)——共振型介质/超材料等效参数的标准色散核，引擎接口
  与 vendor openEMS CalcLorentzMaterial.m 逐式对齐（to_openems 直喂
  AddLorentzMaterial；t_relax=1/(2πγ) 映射）；K-K 自检直接适用。
* **Djordjevic-Sarkar（D-S）**：以 1/f 加权、在 [f1, f2] 上连续叠加 Debye
  弛豫的因果宽带模型 [1]：

      ε(ω) = ε∞ + Δε / ln(f2/f1) · ln[(f2 + j f) / (f1 + j f)]

D-S 的**结构性因果保证**：它等价于无穷多 Debye 极点（每个极点单独满足
Kramers-Kronig 关系）的非负加权叠加，故整体必然满足 K-K。模块另提供
kramers_kronig_residual() 数值自检与 equivalent_debye() 有限多极对照。

多频点向量拟合面（W4-C P13）：``fit_debye_multipoles``（datasheet/Gabriel
组织数据 → 多极 Debye，固定对数极点 + nnls 非负最小二乘，无源性结构
条件由解的非负性保证，拟合质量门 fail-loud）与 ``fit_djordjevic_sarkar_band``
（多点数据 → (ε∞,Δε) 频带拟合）。与池 EC-12（openEMS 渲染通道 Debye，
W2-E 已落 substrate loss_model 旋钮）互补：本批是 core 拟合面，缺省渲染
路径零变化（#329 家法）。Cole-Cole/Havriliak-Negami 分数幂项未落（Gabriel
表消费走 tissue_dielectric.cole_cole_eps），如实留后续增量。

口径与来源（与 openEMS 官方实现逐行对齐）
-----------------------------------------
openEMS 原生支持该模型，接口为
AddDjordjevicSarkarMaterial(CSX, name, 'fMeas', ..., 'epsRMeas', ...,
'tandMeas', ..., 'f1', ..., 'f2', ...)，内部调用
CalcDjordjevicSarkarApprox 由**单频点测量 + 频带端点**拟合：

* 官方文档（确证原生支持）：
  https://openems.readthedocs.io/en/latest/octave/autogenerated/CSXCAD/AddDjordjevicSarkarMaterial.html
* 参考实现（本工作区 vendor）：
  vendor/openEMS/install/share/CSXCAD/matlab/CalcDjordjevicSarkarApprox.m
  单点拟合（lowFreqEvalType=0）：

      k  = ln(10)·(-tanδ·εr - σ_DC/(ε0·ω_m)) / arg[(ω2 + jω_m)/(ω1 + jω_m)]
      ε∞ = εr - k·log10|(ω2 + jω_m)/(ω1 + jω_m)|
      Δε = k·(m2 - m1),   m = log10(ω),  ω = 2πf

* 符号约定：ε = ε' - jε''，tanδ = -Im(ε)/Re(ε) ≥ 0（与 openEMS 一致）。

文献
----
[1] A. R. Djordjevic, R. M. Biljie, V. D. Likar-Smiljanic, T. K. Sarkar,
    "Wideband frequency-domain characterization of FR-4 and time-domain
    causality," IEEE Trans. Electromagn. Compat., vol. 43, no. 4,
    pp. 662-667, 2001.
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from rfauto.core.materials import resolve_materials_yaml_path

__all__ = [
    "C0",
    "EPS0",
    "DebyeModel",
    "DebyePole",
    "DjordjevicSarkar",
    "epsilon_analytic_ds",
    "fit_djordjevic_sarkar",
    "kramers_kronig_residual",
    "load_dispersion_material",
]

#: 真空介电常数 (F/m)，与 openEMS CalcDjordjevicSarkarApprox.m 取值一致
EPS0 = 8.8541878128e-12
#: 真空光速 (m/s)
C0 = 299792458.0


# ─── 输入校验与求值辅助 ────────────────────────────────────────────────────────

def _positive(name: str, value: Any) -> float:
    """校验正的有限标量并返回 float。"""
    out = float(value)
    if not np.isfinite(out) or out <= 0.0:
        raise ValueError(f"{name} 必须为正的有限值，收到 {value!r}")
    return out


def _non_negative(name: str, value: Any) -> float:
    """校验非负的有限标量并返回 float。"""
    out = float(value)
    if not np.isfinite(out) or out < 0.0:
        raise ValueError(f"{name} 必须为非负的有限值，收到 {value!r}")
    return out


def _freq_array(freq_hz: Any) -> tuple[np.ndarray, bool]:
    """把频率入参收敛为 1-D float 数组，并报告原入参是否为标量。"""
    scalar = np.ndim(freq_hz) == 0
    arr = np.atleast_1d(np.asarray(freq_hz, dtype=float))
    if not np.all(np.isfinite(arr)):
        raise ValueError("频率必须为有限值（Hz）")
    if np.any(arr <= 0.0):
        raise ValueError("频率必须为正（Hz）")
    return arr, scalar


def _squeeze(values: np.ndarray, scalar: bool) -> Any:
    """标量输入时把长度为 1 的结果还原为标量。"""
    return values[0] if scalar else values


# ─── Debye 弛豫模型 ───────────────────────────────────────────────────────────

class DebyePole:
    """单个 Debye 弛豫极点：Δε / (1 + j f/f_relax)。"""

    __slots__ = ("delta_eps", "f_relax_hz")

    def __init__(self, delta_eps: float, f_relax_hz: float) -> None:
        self.delta_eps = _positive("delta_eps", delta_eps)
        self.f_relax_hz = _positive("f_relax_hz", f_relax_hz)

    def __repr__(self) -> str:  # pragma: no cover - 可读性辅助
        return f"DebyePole(delta_eps={self.delta_eps!r}, f_relax_hz={self.f_relax_hz!r})"

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, DebyePole):
            return NotImplemented
        return self.delta_eps == other.delta_eps and self.f_relax_hz == other.f_relax_hz


class DebyeModel:
    """单极 / 多极 Debye 复介电常数模型（纯 numpy，确定性）。

    ε(ω) = ε∞ + Σ_i Δε_i / (1 + j ω / ω_i) - j σ_DC/(ω ε0)
    """

    def __init__(self, eps_inf: float, poles: Any = (), sigma_dc: float = 0.0) -> None:
        self.eps_inf = _positive("eps_inf", eps_inf)
        self.sigma_dc = _non_negative("sigma_dc", sigma_dc)
        self.poles = tuple(poles)
        for pole in self.poles:
            if not isinstance(pole, DebyePole):
                raise TypeError(f"poles 元素必须是 DebyePole，收到 {type(pole).__name__}")

    # -- 求值 ---------------------------------------------------------------
    def epsilon(self, freq_hz: Any) -> Any:
        """复相对介电常数 ε = ε' - jε''（标量输入返回标量）。"""
        freq, scalar = _freq_array(freq_hz)
        omega = 2.0 * np.pi * freq
        eps = np.full(freq.shape, complex(self.eps_inf), dtype=complex)
        for pole in self.poles:
            eps = eps + pole.delta_eps / (1.0 + 1j * omega / (2.0 * np.pi * pole.f_relax_hz))
        if self.sigma_dc:
            eps = eps - 1j * self.sigma_dc / (omega * EPS0)
        return _squeeze(eps, scalar)

    def epsilon_r(self, freq_hz: Any) -> Any:
        """实部 ε'(f)。"""
        return np.real(self.epsilon(freq_hz))

    def loss_tangent(self, freq_hz: Any) -> Any:
        """损耗角正切 tanδ = -Im(ε)/Re(ε)。"""
        eps = np.asarray(self.epsilon(freq_hz), dtype=complex)
        return -eps.imag / eps.real

    # -- openEMS 导出 -------------------------------------------------------
    def to_openems(self) -> dict[str, Any]:
        """导出 openEMS AddDebyeMaterial 可直接消费的参数。

        字段对应 openEMS 材料属性：epsilon=ε∞、kappa=σ_DC，
        以及逐极点的 EpsilonDelta_i / EpsilonRelaxTime_i（τ=1/ω_i）。
        """
        return {
            "model": "debye",
            "epsilon": self.eps_inf,
            "kappa": self.sigma_dc,
            "poles": [
                {
                    "delta_eps": pole.delta_eps,
                    "f_relax_hz": pole.f_relax_hz,
                    "relax_time_s": 1.0 / (2.0 * np.pi * pole.f_relax_hz),
                }
                for pole in self.poles
            ],
        }


# ─── Djordjevic-Sarkar 因果宽带模型 ───────────────────────────────────────────

class DjordjevicSarkar:
    """Djordjevic-Sarkar 因果宽带介电模型。

    ε(ω) = ε∞ + Δε/ln(ω2/ω1) · ln[(ω2 + jω)/(ω1 + jω)] - j σ_DC/(ω ε0)

    其中 ω1 = 2π f1、ω2 = 2π f2 是频带端点（D-S 的下/上角频率）。
    """

    def __init__(
        self,
        eps_inf: float,
        delta_eps: float,
        f1_hz: float,
        f2_hz: float,
        sigma_dc: float = 0.0,
        *,
        f_meas_hz: float | None = None,
        eps_r_meas: float | None = None,
        tan_delta_meas: float | None = None,
    ) -> None:
        self.eps_inf = _positive("eps_inf", eps_inf)
        self.delta_eps = _non_negative("delta_eps", delta_eps)
        self.f1_hz = _positive("f1_hz", f1_hz)
        self.f2_hz = _positive("f2_hz", f2_hz)
        if self.f1_hz >= self.f2_hz:
            raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={self.f1_hz!r}, f2={self.f2_hz!r}")
        self.sigma_dc = _non_negative("sigma_dc", sigma_dc)

        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        self.m1 = float(np.log10(omega1))
        self.m2 = float(np.log10(omega2))

        self.f_meas_hz = None if f_meas_hz is None else _positive("f_meas_hz", f_meas_hz)
        self.eps_r_meas = None if eps_r_meas is None else _positive("eps_r_meas", eps_r_meas)
        self.tan_delta_meas = (
            None if tan_delta_meas is None else _non_negative("tan_delta_meas", tan_delta_meas)
        )

    # -- 单点拟合（openEMS 口径）--------------------------------------------
    @classmethod
    def from_single_point(
        cls,
        eps_r: float,
        loss_tangent: float,
        f_meas_hz: float,
        f1_hz: float,
        f2_hz: float,
        sigma_dc: float = 0.0,
    ) -> DjordjevicSarkar:
        """由单频点 (εr, tanδ) + 频带端点 [f1, f2] 反解 D-S 参数。

        与 openEMS CalcDjordjevicSarkarApprox（lowFreqEvalType=0）完全同口径：
        模型在 f_meas 处**精确**回代 εr 与 tanδ。
        """
        eps_r = _positive("eps_r", eps_r)
        loss_tangent = _non_negative("loss_tangent", loss_tangent)
        f_meas = _positive("f_meas_hz", f_meas_hz)
        f1 = _positive("f1_hz", f1_hz)
        f2 = _positive("f2_hz", f2_hz)
        sigma = _non_negative("sigma_dc", sigma_dc)
        if f1 >= f2:
            raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={f1!r}, f2={f2!r}")

        omega1 = 2.0 * np.pi * f1
        omega2 = 2.0 * np.pi * f2
        omega_m = 2.0 * np.pi * f_meas
        m1 = float(np.log10(omega1))
        m2 = float(np.log10(omega2))

        ratio = (omega2 + 1j * omega_m) / (omega1 + 1j * omega_m)
        k = np.log(10.0) * (-loss_tangent * eps_r - sigma / (EPS0 * omega_m)) / np.angle(ratio)
        eps_inf = eps_r - k * np.log10(abs(ratio))
        delta_eps = k * (m2 - m1)

        return cls(
            eps_inf=eps_inf,
            delta_eps=delta_eps,
            f1_hz=f1,
            f2_hz=f2,
            sigma_dc=sigma,
            f_meas_hz=f_meas,
            eps_r_meas=eps_r,
            tan_delta_meas=loss_tangent,
        )

    # -- 求值 ---------------------------------------------------------------
    def epsilon(self, freq_hz: Any) -> Any:
        """复相对介电常数 ε = ε' - jε''（标量输入返回标量）。"""
        freq, scalar = _freq_array(freq_hz)
        omega = 2.0 * np.pi * freq
        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        eps = self.eps_inf + self.delta_eps / (self.m2 - self.m1) * np.log10(
            (omega2 + 1j * omega) / (omega1 + 1j * omega)
        )
        if self.sigma_dc:
            eps = eps - 1j * self.sigma_dc / (omega * EPS0)
        return _squeeze(eps, scalar)

    def epsilon_r(self, freq_hz: Any) -> Any:
        """实部 ε'(f)。"""
        return np.real(self.epsilon(freq_hz))

    def loss_tangent(self, freq_hz: Any) -> Any:
        """损耗角正切 tanδ = -Im(ε)/Re(ε)。"""
        eps = np.asarray(self.epsilon(freq_hz), dtype=complex)
        return -eps.imag / eps.real

    # -- 结构 / 因果 ---------------------------------------------------------
    def static_eps_r(self) -> float:
        """ε(f→0) = ε∞ + Δε（D-S 的 DC 静态值）。"""
        return float(self.eps_inf + self.delta_eps)

    def sarkar_parameters(self) -> dict[str, float]:
        """D-S 原始参数（openEMS paramSarkar 同构）。"""
        return {
            "eps_inf": self.eps_inf,
            "delta_eps": self.delta_eps,
            "f1_hz": self.f1_hz,
            "f2_hz": self.f2_hz,
            "m1": self.m1,
            "m2": self.m2,
            "sigma_dc": self.sigma_dc,
        }

    def equivalent_debye(self, n_terms_per_dec: int = 1) -> DebyeModel:
        """按 openEMS CalcDjordjevicSarkarApprox 口径拟合有限多极 Debye。

        极点对数分布（>=1 个/十倍频程），Δε_i 由 D-S 虚部在对数取样点上的
        线性方程组求得，ε∞ 保证参考频点处实部一致。
        """
        terms = int(n_terms_per_dec)
        if terms < 1:
            raise ValueError(f"n_terms_per_dec 必须 >= 1，收到 {n_terms_per_dec!r}")
        n_terms = int(np.ceil((self.m2 - self.m1) * terms)) + 1
        m_i = np.linspace(self.m1, self.m2, n_terms)
        omega_i = 10.0**m_i
        m_sp = 10.0 ** ((np.log10(omega_i[1]) - np.log10(omega_i[0])) / 4.0)
        omega_meas = omega_i * m_sp

        a = 1.0 / (omega_i[None, :] / omega_meas[:, None] + omega_meas[:, None] / omega_i[None, :])
        eps_pp = -np.imag(self.epsilon(omega_meas / (2.0 * np.pi)))
        delta_eps_i = np.linalg.solve(a, eps_pp)

        f_ref = self.f_meas_hz if self.f_meas_hz is not None else float(np.sqrt(self.f1_hz * self.f2_hz))
        omega_ref = 2.0 * np.pi * f_ref
        sum_real = float(np.sum(delta_eps_i / (1.0 + omega_ref**2 / omega_i**2)))
        omega1 = 2.0 * np.pi * self.f1_hz
        omega2 = 2.0 * np.pi * self.f2_hz
        log_abs = np.log10(abs((omega2 + 1j * omega_ref) / (omega1 + 1j * omega_ref)))
        eps_inf_debye = self.eps_inf + self.delta_eps / (self.m2 - self.m1) * log_abs - sum_real

        poles = [
            DebyePole(delta_eps=float(de), f_relax_hz=float(wi / (2.0 * np.pi)))
            for de, wi in zip(delta_eps_i, omega_i, strict=True)
        ]
        return DebyeModel(eps_inf=float(eps_inf_debye), poles=poles, sigma_dc=self.sigma_dc)

    def to_openems(self, n_terms_per_dec: int = 1) -> dict[str, Any]:
        """导出 openEMS 材料参数（多极 Debye 编码，即官方内部形式）。

        AddDjordjevicSarkarMaterial 内部就是先拟合多极 Debye，再用
        AddDebyeMaterial + EpsilonDelta_i / EpsilonRelaxTime_i 落材料。
        返回值可直接映射到这些 openEMS 材料属性。
        """
        payload = self.equivalent_debye(n_terms_per_dec).to_openems()
        payload["model"] = "djordjevic_sarkar"
        payload["sarkar"] = self.sarkar_parameters()
        return payload

    def to_openems_sarkar_kwargs(self) -> dict[str, Any]:
        """AddDjordjevicSarkarMaterial 的 name-value 参数（单点拟合入口）。

        无测量元数据时取频带几何中点为等价参考点，反解出的 kwargs 可自洽地
        令 openEMS 重新拟合出同一模型。
        """
        if self.f_meas_hz is not None and self.eps_r_meas is not None and self.tan_delta_meas is not None:
            f_ref, eps_r, tan_d = self.f_meas_hz, self.eps_r_meas, self.tan_delta_meas
        else:
            f_ref = float(np.sqrt(self.f1_hz * self.f2_hz))
            eps_r = float(self.epsilon_r(f_ref))
            tan_d = float(self.loss_tangent(f_ref))
        return {
            "fMeas": f_ref,
            "epsRMeas": eps_r,
            "tandMeas": tan_d,
            "f1": self.f1_hz,
            "f2": self.f2_hz,
            "lowFreqEvalType": 0,
            "sigmaDC": self.sigma_dc,
        }


# ─── Lorentz 振子模型（W4-C P13 批 2026-10-05）────────────────────────────────
#
# 引源（#1c）：
# * 模型（标准振子口径，本模块时间约定 e^{+jωt}/ε=ε′−jε″ 与既有 Debye/DS
#   一致；f-form，ω=2πf 已归一）：ε(f) = ε∞ + Σ_i Δε_i·f0_i²/
#   (f0_i² − f² + jf·γ_i) − jσ_DC/(2πf·ε0)。静态极限 ε(0)=ε∞+ΣΔε；
#   谐振点损耗 ε″(f0)=Δε·f0/γ（闭式点锚）；共振介质/超材料等效参数的
#   标准色散核（Lorentz 振子经典口径，教科书级）。
# * 引擎接口单源（与 openEMS 逐式对齐，同既有 DS 面做法）：vendor
#   openEMS CalcLorentzMaterial.m——
#       eps = eps_r − eps_r·Σ (2π·f_p)²/(ω²−(2π·f_L)² − jω·ω_r) − jκ/(ωε0)
#   其中 ω_r=1/t_relax。恒等变换 ε_i·ω0_i²/(ω0_i²−ω²+jωγ_i) ≡
#   −ε∞·ω_p²/(ω²−ω0²−jωγ)（取 ω_p=ω0·sqrt(Δε_i/ε∞)）→ to_openems 导出
#   EpsilonPlasmaFrequency=f0·sqrt(Δε/ε∞)（普通频率，公式内 ×2π）、
#   EpsilonLorPoleFrequency=f0、EpsilonRelaxTime=1/(2π·γ_hz)（秒；γ_hz 为 Hz 频域极点），可直接喂
#   AddLorentzMaterial/CSPropLorentzMaterial。
# * K-K 因果性：Lorentz 核为实冲激响应有理函数（共轭极点对左半平面），
#   kramers_kronig_residual 直接适用（sigma_dc=0 时）。


class LorentzPole:
    """单个 Lorentz 振子：Δε·f0²/(f0² − f² + jf·γ)（f-form，ω=2πf 已归一）。

    delta_eps: 振子强度（≥0）；f0_hz: 固有频率（Hz，>0）；
    gamma_hz: 阻尼系数（Hz，>0；f-form 分母 jf·γ 的直接系数——ω-form 的
    jωγ 之 γ=2π·gamma_hz）。引擎映射：vendor CalcLorentzMaterial 的
    ω·w_r=ω/t_relax 项在 f-form 即 f·(1/(2π·t_relax)) → t_relax=1/(2πγ_hz)
    （to_openems 同式，回代裁判 test 钉）。
    """

    __slots__ = ("delta_eps", "f0_hz", "gamma_hz")

    def __init__(self, delta_eps: float, f0_hz: float, gamma_hz: float) -> None:
        self.delta_eps = _non_negative("delta_eps", delta_eps)
        self.f0_hz = _positive("f0_hz", f0_hz)
        self.gamma_hz = _positive("gamma_hz", gamma_hz)

    def __repr__(self) -> str:  # pragma: no cover - 可读性辅助
        return (
            f"LorentzPole(delta_eps={self.delta_eps!r}, f0_hz={self.f0_hz!r}, "
            f"gamma_hz={self.gamma_hz!r})"
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, LorentzPole):
            return NotImplemented
        return (
            self.delta_eps == other.delta_eps
            and self.f0_hz == other.f0_hz
            and self.gamma_hz == other.gamma_hz
        )


class LorentzModel:
    """单极/多极 Lorentz 振子复介电常数模型（纯 numpy，确定性）。

    ε(ω) = ε∞ + Σ_i Δε_i·ω0_i²/(ω0_i² − ω² + jωγ_i) − jσ_DC/(ωε0)

    接口与 DebyeModel 同构（epsilon/epsilon_r/loss_tangent/to_openems），
    kramers_kronig_residual 直接适用（共振型介质的因果性合格门）。
    """

    def __init__(self, eps_inf: float, poles: Any = (), sigma_dc: float = 0.0) -> None:
        self.eps_inf = _positive("eps_inf", eps_inf)
        self.sigma_dc = _non_negative("sigma_dc", sigma_dc)
        self.poles = tuple(poles)
        for pole in self.poles:
            if not isinstance(pole, LorentzPole):
                raise TypeError(f"poles 元素必须是 LorentzPole，收到 {type(pole).__name__}")

    def epsilon(self, freq_hz: Any) -> Any:
        """复相对介电常数 ε = ε′ − jε″（标量输入返回标量）。"""
        freq, scalar = _freq_array(freq_hz)
        f = freq
        eps = np.full(f.shape, complex(self.eps_inf), dtype=complex)
        for pole in self.poles:
            if pole.delta_eps == 0.0:
                continue
            num = pole.delta_eps * pole.f0_hz * pole.f0_hz
            den = (pole.f0_hz * pole.f0_hz - f * f) + 1j * f * pole.gamma_hz
            eps = eps + num / den
        if self.sigma_dc:
            omega = 2.0 * np.pi * f
            eps = eps - 1j * self.sigma_dc / (omega * EPS0)
        return _squeeze(eps, scalar)

    def epsilon_r(self, freq_hz: Any) -> Any:
        """实部 ε′(f)。"""
        return np.real(self.epsilon(freq_hz))

    def loss_tangent(self, freq_hz: Any) -> Any:
        """损耗角正切 tanδ = −Im(ε)/Re(ε)。"""
        eps = np.asarray(self.epsilon(freq_hz), dtype=complex)
        return -eps.imag / eps.real

    def to_openems(self) -> dict[str, Any]:
        """导出 openEMS AddLorentzMaterial 可直接消费的参数。

        恒等变换（vendor CalcLorentzMaterial.m 口径）：
        EpsilonPlasmaFrequency_n = f0_n·sqrt(Δε_n/ε∞)（普通频率，公式内 ×2π）、
        EpsilonLorPoleFrequency_n = f0_n、EpsilonRelaxTime_n = 1/(2π·γ_hz)。

        推导：引擎 ω-form 阻尼项 ω·ω_r（ω_r=1/t_relax）在 f-form 为
        f/(2π·t_relax)，与本模型 f-form 阻尼 f·γ_hz 对齐 → t_relax=1/(2πγ_hz)。
        """
        return {
            "model": "lorentz",
            "epsilon": self.eps_inf,
            "kappa": self.sigma_dc,
            "poles": [
                {
                    "eps_delta": pole.delta_eps,
                    "f0_hz": pole.f0_hz,
                    "f_plasma_hz": pole.f0_hz * math.sqrt(pole.delta_eps / self.eps_inf),
                    "gamma_hz": pole.gamma_hz,
                    "relax_time_s": 1.0 / (2.0 * np.pi * pole.gamma_hz),
                }
                for pole in self.poles
            ],
        }


# ─── 多频点向量拟合面（W4-C P13：datasheet/Gabriel 数据 → 色散模型）────────────
#
# 确定性线性 LSQ（规则 7）：极点集固定（对数均布于数据带），未知量对复 ε(f)
# 线性——实/虚部堆叠后 nnls（非负最小二乘，保 Δε_i≥0/ε∞≥0/σ≥0 的无源性
# 结构条件，负振子=有源=违反无源性的解直接被排除）。拟合质量门（残差相对
# 量级）fail-loud（同 render_core._debye_pole_fit 0.05 门，坏拟合禁静默）。


def _stack_complex(a: np.ndarray) -> np.ndarray:
    """复设计矩阵 → 实部/虚部堆叠的实矩阵（nnls 入口）。"""
    return np.vstack([np.real(a), np.imag(a)])


def _fit_gate(rel_residual: float, gate: float, ctx: str) -> None:
    if rel_residual > gate:
        raise ValueError(
            f"{ctx}拟合质量门 FAIL：相对残差 {rel_residual:.3g} > {gate:g}"
            "——坏拟合禁静默（#1b 家法），处置=增 n_poles/收窄频带/换模型")


def fit_debye_multipoles(
    freq_hz: Any,
    eps_complex: Any,
    n_poles: int = 4,
    *,
    sigma_dc: bool = False,
    weights: str | None = None,
    f_min_hz: float | None = None,
    f_max_hz: float | None = None,
    max_rel_residual: float = 0.05,
) -> DebyeModel:
    """多频点复 ε(f) 数据 → 多极 Debye 模型（固定对数极点 + nnls 向量拟合）。

    参数：freq_hz/eps_complex 等长 1-D 数组（≥ n_poles+2 点；频率正有限）；
    n_poles 极点数（≥1，对数均布于 [f_min, f_max]——缺省取数据带端点）；
    sigma_dc=True 时增列 −jσ/(ωε0)（σ≥0 由 nnls 保证）；weights=None（缺省，
    绝对残差 LSQ）| "relative"（逐点 1/|ε_data| 加权——宽频带含 σ_DC 尾时
    绝对残差被低频大 |ε″| 支配，相对加权恢复中高频约束力，确定性同规则 7）；
    max_rel_residual 拟合质量门（超门 ValueError，缺省 0.05 与
    render_core._debye_pole_fit 同口径；加权门按加权范数计）。

    返回 DebyeModel（eps_inf/poles/sigma_dc 均非负——无源性结构条件由
    nnls 保证）。合成回收裁判与 Gabriel 组织数据真实数据锚见
    tests/unit/test_w4_c_p13_dispersion.py。
    """
    from scipy.optimize import nnls

    freq, _ = _freq_array(freq_hz)
    eps = np.atleast_1d(np.asarray(eps_complex, dtype=complex))
    if eps.shape != freq.shape:
        raise ValueError(f"freq_hz/eps_complex 须等长一维，得 {freq.size}/{eps.size}")
    if np.any(~np.isfinite(eps)):
        raise ValueError("eps_complex 必须全为有限值")
    n = int(n_poles)
    if n < 1:
        raise ValueError(f"n_poles 必须 >=1，收到 {n_poles!r}")
    if freq.size < n + 2:
        raise ValueError(
            f"数据点数须 ≥ n_poles+2（过定），得 {freq.size} 点/{n} 极")
    f_lo = float(np.min(freq)) if f_min_hz is None else _positive("f_min_hz", f_min_hz)
    f_hi = float(np.max(freq)) if f_max_hz is None else _positive("f_max_hz", f_max_hz)
    if f_hi <= f_lo:
        raise ValueError(f"要求 f_max_hz > f_min_hz，得 [{f_lo!r}, {f_hi!r}]")
    if freq.size and (np.min(freq) < f_lo - 1e-12 * f_lo or np.max(freq) > f_hi + 1e-12 * f_hi):
        raise ValueError("数据频率越出 [f_min_hz, f_max_hz] 拟合带")
    gate = _positive("max_rel_residual", max_rel_residual)

    omega = 2.0 * np.pi * freq
    tau = 1.0 / (2.0 * np.pi * np.geomspace(f_lo, f_hi, n))
    cols = [np.ones_like(omega, dtype=complex)]
    cols += [1.0 / (1.0 + 1j * omega * t) for t in tau]
    if sigma_dc:
        cols.append(-1j / (omega * EPS0))
    a = _stack_complex(np.column_stack(cols))
    b = np.concatenate([np.real(eps), np.imag(eps)])
    if weights is None:
        w_vec = np.ones_like(b)
    elif weights == "relative":
        w_vec = 1.0 / np.abs(eps)
        w_vec = np.concatenate([w_vec, w_vec])
    else:
        raise ValueError(f"weights 只收 None/'relative'，收到 {weights!r}")
    x, _ = nnls(a * w_vec[:, None], b * w_vec)
    rel = float(np.linalg.norm((a @ x - b) * w_vec) / np.linalg.norm(b * w_vec))
    _fit_gate(rel, gate, "debye 多极")
    eps_inf = float(x[0])
    poles = [
        DebyePole(delta_eps=float(v), f_relax_hz=float(1.0 / (2.0 * np.pi * t)))
        for v, t in zip(x[1:1 + n], tau, strict=True)
        if float(v) > 0.0  # nnls 零振子极点剪枝（DebyePole 只收正 Δε）
    ]
    sigma = float(x[1 + n]) if sigma_dc else 0.0
    return DebyeModel(eps_inf=eps_inf, poles=poles, sigma_dc=sigma)


def fit_djordjevic_sarkar_band(
    freq_hz: Any,
    eps_complex: Any,
    f1_hz: float,
    f2_hz: float,
    *,
    sigma_dc: float = 0.0,
    max_rel_residual: float = 0.05,
) -> DjordjevicSarkar:
    """多频点复 ε(f) 数据 → D-S 频带模型（(ε∞, Δε) 两参数线性 nnls 拟合）。

    与 from_single_point（单点精解）互补：多点数据下同一 (f1,f2) 带内
    最小二乘定 (ε∞, Δε)；σ_DC 作已知量先扣（非线性入参，不做拟合变量）。
    质量门同 fit_debye_multipoles。
    """
    from scipy.optimize import nnls

    freq, _ = _freq_array(freq_hz)
    eps = np.atleast_1d(np.asarray(eps_complex, dtype=complex))
    if eps.shape != freq.shape:
        raise ValueError(f"freq_hz/eps_complex 须等长一维，得 {freq.size}/{eps.size}")
    if np.any(~np.isfinite(eps)):
        raise ValueError("eps_complex 必须全为有限值")
    if freq.size < 4:
        raise ValueError(f"数据点数须 ≥4（两参数过定），得 {freq.size}")
    sigma = _non_negative("sigma_dc", sigma_dc)
    gate = _positive("max_rel_residual", max_rel_residual)
    f1 = _positive("f1_hz", f1_hz)
    f2 = _positive("f2_hz", f2_hz)
    if f1 >= f2:
        raise ValueError(f"要求 f1_hz < f2_hz，得 [{f1!r}, {f2!r}]")

    omega = 2.0 * np.pi * freq
    omega1 = 2.0 * np.pi * f1
    omega2 = 2.0 * np.pi * f2
    m1 = float(np.log10(omega1))
    m2 = float(np.log10(omega2))
    kernel = np.log10((omega2 + 1j * omega) / (omega1 + 1j * omega)) / (m2 - m1)
    target = eps.copy()
    if sigma:
        target = target - 1j * sigma / (omega * EPS0)
    a = _stack_complex(np.column_stack([np.ones_like(omega, dtype=complex), kernel]))
    b = np.concatenate([np.real(target), np.imag(target)])
    x, _ = nnls(a, b)
    rel = float(np.linalg.norm(a @ x - b) / np.linalg.norm(b))
    _fit_gate(rel, gate, "D-S 频带")
    return DjordjevicSarkar(
        eps_inf=float(x[0]), delta_eps=float(x[1]), f1_hz=f1, f2_hz=f2,
        sigma_dc=sigma,
    )


# ─── 独立解析对照（复对数路径之外的实/虚部闭式）──────────────────────────────

def epsilon_analytic_ds(
    eps_inf: float,
    delta_eps: float,
    f1_hz: float,
    f2_hz: float,
    freq_hz: Any,
    sigma_dc: float = 0.0,
) -> Any:
    """D-S 的实/虚部独立闭式（不含 np.log 复数路径，供交叉校验）。

        ε'(ω) = ε∞ + Δε/ln(ω2/ω1) · ½ln[(ω2²+ω²)/(ω1²+ω²)]
        ε''(ω) = Δε/ln(ω2/ω1) · [arctan(ω/ω1) - arctan(ω/ω2)]
    """
    eps_inf = _positive("eps_inf", eps_inf)
    delta_eps = _non_negative("delta_eps", delta_eps)
    f1 = _positive("f1_hz", f1_hz)
    f2 = _positive("f2_hz", f2_hz)
    sigma = _non_negative("sigma_dc", sigma_dc)
    if f1 >= f2:
        raise ValueError(f"要求 f1_hz < f2_hz，收到 f1={f1!r}, f2={f2!r}")

    freq, scalar = _freq_array(freq_hz)
    omega = 2.0 * np.pi * freq
    omega1 = 2.0 * np.pi * f1
    omega2 = 2.0 * np.pi * f2
    ln_ratio = np.log(omega2 / omega1)

    eps_real = eps_inf + delta_eps / ln_ratio * 0.5 * np.log((omega2**2 + omega**2) / (omega1**2 + omega**2))
    eps_imag = delta_eps / ln_ratio * (np.arctan(omega / omega2) - np.arctan(omega / omega1))
    eps = eps_real + 1j * eps_imag
    if sigma:
        eps = eps - 1j * sigma / (omega * EPS0)
    return _squeeze(eps, scalar)


def fit_djordjevic_sarkar(
    eps_r: float,
    loss_tangent: float,
    f_meas_hz: float,
    f1_hz: float,
    f2_hz: float,
    sigma_dc: float = 0.0,
) -> DjordjevicSarkar:
    """由单频点 (εr, tanδ) + 频带端点拟合 D-S 模型（from_single_point 别名）。"""
    return DjordjevicSarkar.from_single_point(eps_r, loss_tangent, f_meas_hz, f1_hz, f2_hz, sigma_dc)


# ─── Kramers-Kronig 数值自检 ─────────────────────────────────────────────────

def kramers_kronig_residual(
    model: DebyeModel | DjordjevicSarkar | LorentzModel,
    freq_hz: Any,
    *,
    n_points: int = 100001,
    span_decades: float = 20.0,
) -> Any:
    """在主值意义下数值检验实部 K-K 关系，返回相对残差。

        ε'(ω) - ε∞ = (2/π) P ∫_0^∞ ξ ε''(ξ)/(ξ² - ω²) dξ

    积分经 t = ln(ξ/ω) 换元后核函数为奇函数，对称半格点梯形求积可消去
    1/(2t) 主值奇异项。要求 σ_DC = 0（电导项的 K-K 需额外减除项）。
    """
    if getattr(model, "sigma_dc", 0.0) != 0.0:
        raise ValueError("K-K 自检要求 sigma_dc=0（电导项的 K-K 需额外减除项）")
    n = int(n_points)
    if n < 1001:
        raise ValueError(f"n_points 必须 >= 1001，收到 {n_points!r}")
    span = _positive("span_decades", span_decades)
    eps_inf = _positive("eps_inf", model.eps_inf)

    freq, scalar = _freq_array(freq_hz)
    t_max = span * np.log(10.0)
    t = (np.arange(-n, n) + 0.5) * (t_max / n)
    kernel = 1.0 / (1.0 - np.exp(-2.0 * t))

    residual = np.empty(freq.shape, dtype=float)
    for idx, f0 in enumerate(freq):
        xi = f0 * np.exp(t)
        eps_xi = np.asarray(model.epsilon(xi), dtype=complex)
        lhs = (2.0 / np.pi) * np.trapezoid(-eps_xi.imag * kernel, t)
        eps_at = complex(np.asarray(model.epsilon(f0), dtype=complex))
        rhs = eps_at.real - eps_inf
        residual[idx] = abs(lhs - rhs) / abs(rhs) if rhs != 0.0 else abs(lhs)
    return _squeeze(residual, scalar)


# ─── materials.yaml 色散条目加载 ─────────────────────────────────────────────

def _materials_path(config_path: str | Path | None) -> Path:
    # AU-5 单点：发现顺序（显式→env→向上）收敛 core/materials；
    # 函数名/签名保留（service/dispersion_service 既有引用）。
    return resolve_materials_yaml_path(config_path)


def load_dispersion_material(
    name: str,
    config_path: str | Path | None = None,
) -> DjordjevicSarkar:
    """从 configs/materials.yaml 的 dispersion 子段构造 D-S 模型。"""
    path = _materials_path(config_path)
    if not path.exists():
        raise FileNotFoundError(f"materials.yaml 不存在: {path}")
    with open(path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}

    materials = data.get("materials", {})
    if name not in materials:
        raise KeyError(f"未知材料: {name}，可用: {list(materials)}")
    block = materials[name].get("dispersion")
    if not block:
        raise KeyError(f"材料 {name} 没有 dispersion 条目")

    model = str(block.get("model", "")).strip().lower()
    if model != "djordjevic_sarkar":
        raise ValueError(f"不支持的色散模型: {model!r}（材料 {name}）")

    return DjordjevicSarkar.from_single_point(
        eps_r=float(block["eps_r_meas"]),
        loss_tangent=float(block["tan_delta_meas"]),
        f_meas_hz=float(block["f_meas_hz"]),
        f1_hz=float(block["f1_hz"]),
        f2_hz=float(block["f2_hz"]),
        sigma_dc=float(block.get("sigma_dc", 0.0)),
    )
