"""QIF 3.0 特性清单 XML（ISO 23952 简化子集）+ CAM 工艺说明（L0 纯渲染）.

写盘包装在 adapters/fab_export/qif_io.py。
"""

from __future__ import annotations

from collections.abc import Iterable
from datetime import datetime, timezone
from xml.sax.saxutils import escape

from .schema import CriticalChar, DimsDocument


def render_qif_characteristics(
    chars: Iterable[CriticalChar],
    *,
    part_id: str,
    units: str = "mm",
    now: str | None = None,
) -> str:
    """渲染简化的 QIF 风格 Characteristics XML（检验计划可读）.

    非完整 QIF 3.0 全 schema，字段与 critical_chars 对齐，便于 CMM/数字化线接入。
    ``now`` 供测试注入固定时间戳。
    """
    now_s = now or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<Characteristics xmlns="http://www.qifstandards.org/schema/qif3" version="3.0" id="1">',
        "  <Header>",
        f"    <Name>{escape(part_id)} Manufacturing Characteristics</Name>",
        "    <Description>Generated by fab_export; nominal from HFSS dims</Description>",
        "    <Application>fab_export</Application>",
        "    <Author>fab_export</Author>",
        f"    <Created>{now_s}</Created>",
        "  </Header>",
        "  <CharacteristicDefinitions>",
    ]
    for i, c in enumerate(chars, 1):
        nom = "" if c.nominal is None else f"{c.nominal:.6f}"
        lines += [
            f'    <CharacteristicDef id="{i}" type="Linear">',
            f"      <Name>{escape(c.char_id)} {escape(c.feature)}</Name>",
            f"      <KeyCharacteristic>{escape(c.source_var)}</KeyCharacteristic>",
            "      <LinearCharacteristic>",
            f"        <TargetValue>{nom}</TargetValue>",
            f'        <Tolerance><PlusMinus><Limit>{abs(c.tol_plus):.6f}</Limit></PlusMinus></Tolerance>',
            f'        <DatumReference>{escape(c.datum or "A")}</DatumReference>',
            "      </LinearCharacteristic>",
            "    </CharacteristicDef>",
        ]
    lines += ["  </CharacteristicDefinitions>", "</Characteristics>"]
    return "\n".join(lines) + "\n"


def render_cam_notes(
    dims: DimsDocument,
    *,
    process_by_feature: dict[str, str] | None = None,
) -> str:
    """CAM/工艺说明 Markdown 文本（给 Mastercam/UG/线切割）."""
    process_by_feature = process_by_feature or {}
    lines = [
        f"# CAM 工艺说明 — {dims.part_id} Rev{dims.rev}",
        "",
        f"- 单位: {dims.units}（禁止再缩放）",
        f"- 坐标系: {dims.wcs}",
        "",
        "## 特征与建议工序",
        "",
        "| 特征 | 值(mm) | 工序 | 备注 |",
        "|------|--------|------|------|",
    ]
    for v in dims.variables:
        proc = process_by_feature.get(v.name, "")
        if not proc:
            low = v.name.lower()
            if "iris" in low or "window" in low:
                proc = "WEDM 慢走丝"
            elif v.tol_class == "PIN_H7":
                proc = "钻铰 H7"
            elif "thread" in low:
                proc = "攻丝 6H"
            else:
                proc = "3轴铣 2.5D"
        lines.append(f"| {v.drawing_label or v.name} | {v.value:g} | {proc} | tol={v.tol_class} |")
    lines += [
        "",
        "## 通用",
        "- 装夹: 法兰贴合面为基准 A",
        "- 深腔/窄槽: 优先 WEDM 或小刀+清角",
        "- 余量: 精加工 0.1–0.2 mm",
        "- 检验: 见 critical_chars.csv 与 qif_characteristics.xml",
        "- 变更: 只回写 HFSS 变量后重导，禁止车间改关键尺寸",
    ]
    return "\n".join(lines) + "\n"


def render_mbd_note(part_id: str) -> str:
    """MBD/3D 补充说明 Markdown 文本（2D 仍是合同）."""
    return f"""# MBD 说明 — {part_id}

- 本包以 **2D PDF/DXF 为合同图纸**。
- STEP/x_t 为 CAM 主数据；若厂家有 PMI 能力，可在 NX/Creo 中按 critical_chars 添加 3D 标注。
- 完整 QIF 3.0 / 3D PDF 需厂家或 CAD 侧工具；本包提供 qif_characteristics.xml 特性清单作为过渡。
- 禁止仅凭 STEP 量尺寸替代 dims.json。
"""
