"""SV-1：scuff-em 表面积分方程（MoM/RWG）适配器——GPL 隔离子进程通道。

规格（round14 §六 SV-1）："子进程 CLI 通道（GPL 隔离同 openEMS/qucsator
模式）；波导端口 S 参数+FSS 透射。验收：PEC 方板单站 RCS vs 闭式、
ms_cross vs PSSFSS Δf≤5%、HFSS 仲裁。表面积分方程法=仓内唯一整块
缺失的数值方法面。"

许可边界（写死 fail-closed，:mod:`rfauto.adapters.gpl.license_gate`）：
scuff-em 为 GPL-2/3——本适配器**只**经子进程调用 ``scuff-scatter`` 可
执行文件（mere aggregation 边界），从不 import scuff-em 的 Python 绑定
（进程内链接即 GPL 传染面）；且 solve 前必须过显式 opt-in 许可门
（缺省拒绝）。

可执行解析链：env ``RFAUTO_SCUFF_EXE`` → PATH which（``scuff-scatter``）。
全落空 = is_available False / connect False（不静默降级）。

输入生成（确定性纯函数，离线可测）：
- :func:`write_freq_file`：扫频文件（scuff-em ``--freqfile`` 惯例：每行
  一个频率或 "f0 f1 N" 区间对）；
- :func:`write_scuffgeo`：最小 PEC 表面 .scuffgeo 文本（SURFACE 段引用
  调用方提供的 gmsh msh 网格——网格生成不属本适配器职责）；
- :func:`build_scatter_command`：``scuff-scatter`` 命令行构造
  （--geometry/--freqfile/--FOM SParams，输出目录经 --cache（scuff-em
  约定为结果目录参数，真机实录项，见下）。

诚实边界（#122 / #215 禁臆写）：
- **S 参数解析器为待证档**：:func:`parse_sparam_pairs` 按"4 列空白
  分隔数值行（port_i port_j Re Im）+ # 注释"的假设约定解析，真机
  scuff-scatter 实际列序未经本机实录核对（引擎未安装）——解析器对
  形态不符一律 fail-closed 报错，绝不猜列；真机接通后按实录修列序
  并摘除本标注。
- round14 验收（RCS vs 闭式 / ms_cross vs PSSFSS / HFSS 仲裁）= 真机
  面，走 env 显式意图门的 opt-in 测试（skipif 引擎缺席），不进 unit 门。
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
from collections.abc import Mapping
from pathlib import Path
from typing import Any, ClassVar

import numpy as np

from rfauto.adapters.em_solver_base import (
    EMSolverAdapter,
    EMSolverConfig,
    EMSolverResult,
    SolverCapabilities,
)
from rfauto.adapters.gpl.license_gate import require_gpl_channel

logger = logging.getLogger(__name__)

#: env 显式 exe 覆盖
SCUFF_ENV_VAR = "RFAUTO_SCUFF_EXE"
#: PATH 候选二进制（scuff-em 套件主入口）
SCUFF_BINARIES: tuple[str, ...] = ("scuff-scatter", "scuff-scatter.exe")
#: 子进程超时缺省（秒；extra_params["timeout_s"] 可覆盖）
DEFAULT_TIMEOUT_S = 600.0


def resolve_scuff_exe(environ: Mapping[str, str] | None = None) -> str | None:
    """scuff-em 可执行解析链：显式 env → PATH which（无则 None）。"""
    src = os.environ if environ is None else environ
    explicit = src.get(SCUFF_ENV_VAR)
    if explicit:
        if Path(explicit).exists():
            return str(Path(explicit))
        logger.warning("%s 指向不存在的路径: %s（忽略，继续 which）",
                       SCUFF_ENV_VAR, explicit)
    for cand in SCUFF_BINARIES:
        resolved = shutil.which(cand)
        if resolved:
            return resolved
    return None


def write_freq_file(
    path: Path, freq_ghz: tuple[float, float, int],
) -> Path:
    """scuff-em ``--freqfile`` 文本（每行一对 f0 f1，GHz 值由调用方换算）。"""
    f0, f1, n = float(freq_ghz[0]), float(freq_ghz[1]), int(freq_ghz[2])
    if n < 1 or not 0.0 < f0 <= f1:
        raise ValueError(f"扫频参数非法: {freq_ghz!r}")
    lines = [f"{f0} {f1}" if n == 1 else
             f"{f0 + (f1 - f0) * k / (n - 1)} {f0 + (f1 - f0) * k / (n - 1)}"
             for k in range(n)]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def write_scuffgeo(
    path: Path,
    surfaces: list[dict[str, Any]],
) -> Path:
    """最小 PEC .scuffgeo 文本（SURFACE 段引用调用方提供的 msh 网格）。

    surfaces 逐项 {"name": str, "mesh_file": str, "material": "PEC"}；
    材料缺省 PEC。真机口径（.scuffgeo 语法）以 scuff-em 官方文档为准，
    本生成面只覆盖"PEC 表面 + MESHFILE 引用"最小族（待真机实录扩面）。
    """
    if not surfaces:
        raise ValueError("surfaces 不得为空（scuffgeo 至少一个 SURFACE）")
    out = ["# generated by rfauto adapters/gpl/scuff_adapter (SV-1)"]
    for s in surfaces:
        name = str(s.get("name", "")).strip()
        mesh = str(s.get("mesh_file", "")).strip()
        material = str(s.get("material", "PEC")).strip().upper()
        if not name or not mesh:
            raise ValueError(f"SURFACE 项缺 name/mesh_file: {s!r}")
        out.append(f"SURFACE {name}")
        out.append(f"  MESHFILE {mesh}")
        if material != "PEC":
            out.append(f"  OBJMATERIAL {material}")
        out.append("ENDSURFACE")
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    return path


def build_scatter_command(
    exe: str,
    geo_file: Path,
    freq_file: Path,
    work_dir: Path,
) -> list[str]:
    """scuff-scatter 命令行（FOM=SParams；输出落 work_dir）。"""
    return [
        str(exe),
        "--geometry", str(geo_file),
        "--freqfile", str(freq_file),
        "--FOM", "SParams",
        "--cache", str(work_dir),
    ]


def parse_sparam_pairs(
    text: str, n_ports: int,
) -> tuple[np.ndarray, np.ndarray]:
    """待证档 S 参数解析（fail-closed：形态不符显式报错，不猜列）。

    假设约定（真机实录项，见模块 docstring 诚实边界）：行格式
    ``<port_i> <port_j> <Re> <Im>``（1 基端口号，空白分隔，# 注释行，
    按出现顺序即频率顺序）。返回 (freq-无关的) s_params
    (n_freq, n_ports, n_ports) complex——本函数只收端口号 1..n_ports，
    越界/列数不对/非数值一律 ValueError。
    """
    per_freq: list[np.ndarray] = []
    current: list[tuple[int, int, float, float]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) != 4:
            raise ValueError(
                f"parse_sparam_pairs 期望 4 列（i j Re Im），实得 {len(parts)}"
                f" 列: {line!r}（列序为待证约定，真机实录后修订）")
        try:
            i, j = int(parts[0]), int(parts[1])
            re_v, im_v = float(parts[2]), float(parts[3])
        except ValueError as exc:
            raise ValueError(f"非数值字段: {line!r}") from exc
        if not (1 <= i <= n_ports and 1 <= j <= n_ports):
            raise ValueError(
                f"端口号越界 {i},{j}（n_ports={n_ports}）")
        current.append((i, j, re_v, im_v))
        if len(current) == n_ports * n_ports:
            mat = np.zeros((n_ports, n_ports), dtype=complex)
            for pi, pj, rv, iv in current:
                mat[pi - 1, pj - 1] = complex(rv, iv)
            per_freq.append(mat)
            current = []
    if current:
        raise ValueError(
            "末尾残缺频率块（不足 n_ports² 行）——fail-closed 不猜补")
    if not per_freq:
        raise ValueError("无有效 S 参数行")
    return np.stack(per_freq)


class ScuffAdapter(EMSolverAdapter):
    """scuff-em 表面积分方程通道（子进程；GPL fail-closed 门强制前置）。"""

    #: 能力声明（如实：当前覆盖 SParams FOM 最小族——波导端口 S 参数/
    #: FSS 透射建到「端口族=调用方透传」层；RCS/远场/模板/并行面未
    #: 实现 → False；license 面=GPL 免费但 fail-closed opt-in 门）
    CAPABILITIES: ClassVar[SolverCapabilities] = SolverCapabilities(
        solver_type="scuff",
        supports_wave_port=True,
        supports_lumped_port=False,
        supports_field_export=False,
        supports_convergence_report=False,
        supports_touchstone_export=False,
        supports_headless_solve=True,
        supports_optimetrics=False,
        dimension="3d",
        material_models=("pec",),
        parallel_backends=(),
        supports_sar=False,
        supports_nf2ff=False,
        supports_lumped_elements=False,
        supported_templates=(),
        requires_license=False,
        availability_gate="gpl_optin+exe_path",
    )

    def __init__(self, config: EMSolverConfig):
        super().__init__(config)
        self._exe_path: str | None = config.exe_path
        self._geo: dict[str, Any] | None = None
        self._last_result: tuple[np.ndarray, np.ndarray] | None = None

    # ── 可用性 / 连接（连接点=许可门执行点）───────────────────────────
    def is_available(self) -> bool:
        exe = self._exe_path or resolve_scuff_exe()
        return exe is not None and Path(exe).exists()

    def connect(self) -> bool:
        # GPL fail-closed 门：缺省拒绝（LicenseRefusedError 带 remedy）。
        require_gpl_channel("scuff")
        exe = self._exe_path or resolve_scuff_exe()
        if exe is None or not Path(exe).exists():
            return False
        self._exe_path = exe
        self._connected = True
        return True

    # ── 几何/求解/提取 ────────────────────────────────────────────────
    def build_geometry(self, geometry: dict[str, Any]) -> bool:
        """geometry: {"surfaces": [...], "freq_ghz": (f0, f1, n)}——文本
        产物落 working_dir（scuffgeo + freqfile）。"""
        if not self._connected:
            return False
        work = Path(self._config.working_dir or ".").resolve()
        work.mkdir(parents=True, exist_ok=True)
        try:
            self._geo_file = write_scuffgeo(
                work / "rfauto.scuffgeo",
                list(geometry.get("surfaces") or []))
            self._freq_file = write_freq_file(
                work / "rfauto.freq",
                tuple(geometry.get("freq_ghz") or
                      (self._config.freq_range_ghz[0],
                       self._config.freq_range_ghz[1], 11)))
        except (ValueError, KeyError, TypeError) as exc:
            logger.error("scuffgeo/freq 生成失败: %s", exc)
            return False
        self._geo = dict(geometry)
        return True

    def solve(self) -> EMSolverResult:
        """子进程执行 scuff-scatter（GPL 隔离交互点；超时/非零退出如实失败）。"""
        import time

        if not self._connected or self._geo is None:
            return EMSolverResult(success=False,
                                  message="scuff 未连接或未 build_geometry")
        timeout = float(
            (self._config.extra_params or {}).get("timeout_s",
                                                  DEFAULT_TIMEOUT_S))
        cmd = build_scatter_command(
            self._exe_path or "", self._geo_file, self._freq_file,
            Path(self._config.working_dir or ".").resolve())
        t0 = time.monotonic()
        try:
            proc = subprocess.run(
                cmd, capture_output=True, text=True, timeout=timeout,
                check=False, encoding="utf-8", errors="replace")
        except subprocess.TimeoutExpired:
            return EMSolverResult(success=False,
                                  message=f"scuff-scatter 超时（>{timeout:g}s）")
        wall = time.monotonic() - t0
        if proc.returncode != 0:
            return EMSolverResult(
                success=False, wall_time_s=wall,
                message=f"scuff-scatter rc={proc.returncode}: "
                        f"{(proc.stderr or '')[-500:]}")
        out_file = (Path(self._config.working_dir or ".") / "SParams")
        if not out_file.exists():
            return EMSolverResult(
                success=False, wall_time_s=wall,
                message="scuff-scatter 未产出 SParams（输出约定待真机实录）")
        n_ports = int((self._geo or {}).get("n_ports", 2))
        try:
            s_params = parse_sparam_pairs(
                out_file.read_text(encoding="utf-8"), n_ports)
        except ValueError as exc:
            return EMSolverResult(
                success=False, wall_time_s=wall,
                message=f"SParams 解析失败（fail-closed）: {exc}")
        self._last_result = (self._freq_axis(), s_params)
        return EMSolverResult(
            success=True, freq_ghz=self._freq_axis(), s_params=s_params,
            wall_time_s=wall, message="ok（解析档=待证约定，见 docstring）")

    def _freq_axis(self) -> np.ndarray:
        f0, f1, n = self._freq_args()
        return np.linspace(f0, f1, n)

    def _freq_args(self) -> tuple[float, float, int]:
        raw = self._geo.get("freq_ghz") if self._geo else None
        if raw:
            return float(raw[0]), float(raw[1]), int(raw[2])
        cfg = self._config.freq_range_ghz
        return float(cfg[0]), float(cfg[1]), 11

    def get_sparams(self) -> tuple[np.ndarray, np.ndarray]:
        if self._last_result is None:
            raise RuntimeError("scuff: 无可用求解结果（先 solve）")
        return self._last_result

    def close(self) -> None:
        self._connected = False


def register_scuff(registry: Any | None = None) -> None:
    """注册 scuff 通道（自定义字符串键；import rfauto.adapters.gpl 即注册）。"""
    from rfauto.adapters.em_solver_base import get_global_registry

    target = registry or get_global_registry()
    target.register("scuff", ScuffAdapter)


register_scuff()
